
services:
  db:
    image: mysql:8.0
    container_name: voterow-db
    restart: always
    environment:
      MYSQL_DATABASE: voterow_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - voterow-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: voterow-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/voterow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - voterow-net

  frontend:
    build:
      context: .
      dockerfile: voterow/Dockerfile.frontend
    container_name: voterow-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - voterow-net

volumes:
  db_data:

networks:
  voterow-net:
    driver: bridge
